=== amritansha28/Internet_And_Web_Programming/IWP_DA3/movies.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT movies ((moviename)+)>
<!ELEMENT moviename (title,genre,releasedate,releaseyear,language)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT releasedate (#PCDATA)>
<!ELEMENT releaseyear (#PCDATA)>
<!ELEMENT language (#PCDATA)>

=== amritansha28/Internet_And_Web_Programming/IWP_DA3/movies.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<!DOCTYPE movies SYSTEM "movies.dtd">
<movies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="movies.xsd">
    <moviename>
        <title>Uri</title>
        <genre>Thriller</genre>
        <releasedate>2019-01-10</releasedate>
        <releaseyear>2019</releaseyear>
        <language>Hindi</language>
    </moviename>
    <moviename>
        <title>Lootcase</title>
        <genre>Thriller</genre>
        <releasedate>2020-07-31</releasedate>
        <releaseyear>2020</releaseyear>
        <language>English</language>
    </moviename>
        <moviename>
        <title>Pushpa</title>
        <genre>Action</genre>
        <releasedate>2021-12-17</releasedate>
        <releaseyear>2021</releaseyear>
        <language>Tamil</language>
    </moviename>
</movies>
